apiVersion: apps/v1
kind: Deployment
metadata:
  name: analyzer
  labels:
    app: analyzer
spec:
  selector:
    matchLabels:
      app: analyzer
  replicas: 1
  template:
    metadata:
      labels:
        app: analyzer
    spec:
      containers:
      - name: analyzer
        image: ibmcom/analyzer:v1
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        env:
        - name: VCAP_SERVICES_TONE_ANALYZER_0_CREDENTIALS_USERNAME
          value: b01802b8-7860-4707-9e21-b2407f890501
        - name: VCAP_SERVICES_TONE_ANALYZER_0_CREDENTIALS_PASSWORD
          value: 0C35gdtNw3Wm
        - name: USE_HTTPS
          value: "True"
        ports:
        - containerPort: 5000
          name: http
